# Generated by Django 2.1 on 2018-08-25 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categroy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='big_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_big', to='article.Image', verbose_name='文章列表展示大图'),
        ),
        migrations.AddField(
            model_name='article',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categroy.Categroy', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='small_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_small', to='article.Image', verbose_name='文章列表展示小图'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='文章标签'),
        ),
    ]
