# Generated by Django 2.1 on 2018-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180816_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=300, verbose_name='文章摘要'),
        ),
    ]
