# Generated by Django 2.1 on 2018-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='图片描述'),
        ),
    ]
