# Generated by Django 2.1 on 2018-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_content',
            field=models.TextField(default='', verbose_name='文章html渲染内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='md_content',
            field=models.TextField(default='', verbose_name='文章markdown原始内容'),
        ),
    ]
